---
- name: Update packages on Ubuntu hosts
  hosts: all
  gather_facts: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Send a message to the Discord channel
      community.general.discord:
        webhook_id: "1194033882794823761"
        webhook_token: "LSXLk6I9f2gAJzRSllboKfqoLBaB7YwTeFXjdVEmTLt2lcx8W1XknKYKiQutQFDo96GO"
        content: "Software update complete on {{ ansible_hostname }}."
